name: Build and publish python package

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check MAJOR changes
        if: "startsWith(github.event.pull_request.title, 'feat!:')"
        run: echo "VERSION_COMPONENT=--major" >> env.GITHUB_ENV
      - name: Check MINOR changes
        if: "startsWith(github.event.pull_request.title, 'feat:')"
        run: echo "VERSION_COMPONENT=--minor" >> env.GITHUB_ENV
      - name: Check PATCH changes
        if: "startsWith(github.event.pull_request.title, 'fix:')"
        run: echo "VERSION_COMPONENT=--patch" >> env.GITHUB_ENV
      - name: Bump version
        run: bumpver update --env.VERSION_COMPONENT
