name: Build and publish python package

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Print head commit message
        run: echo '${{ github.event.head_commit.message }}'
      - name: Check MAJOR changes
        if: "startsWith(github.event.head_commit.message, 'feat!:')"
        run: echo "VERSION_COMPONENT=--major" >> $env:GITHUB_ENV
      - name: Check MINOR changes
        if: "startsWith(github.event.head_commit.message, 'feat:')"
        run: echo "VERSION_COMPONENT=--minor" >> $env:GITHUB_ENV
      - name: Check PATCH changes
        if: "startsWith(github.event.head_commit.message, 'fix:')"
        run: echo "VERSION_COMPONENT=--patch" >> $env:GITHUB_ENV
      - name: Print VERSION_COMPONENT
        run: echo $env:VERSION_COMPONENT
